spring:
  datasource:
    hikari:
      connection-test-query: SELECT 1
  jpa:
    database: MYSQL
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: true
    hibernate:
      use-new-id-generator-mappings: false

mybatis:
  configuration:
    map-underscore-to-camel-case: true

logging:
  config: classpath:logback-${spring.profiles.active}.xml

---
spring:
  profiles: dev
  datasource:
    hikari:
      driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      jdbc-url: jdbc:log4jdbc:mysql://10.177.55.244:3306/insight?useUnicode=true&characterEncoding=utf-8
      password: Dldpdl123!
      username: catos
  resources:
    cache:
      period: 0
  thymeleaf:
    cache: false

---
spring:
  profiles: prod
  datasource:
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://10.177.55.244:3306/insight?useUnicode=true&characterEncoding=utf-8
      password: Dldpdl123!
      username: catos
